### ISSUE TITLE
The type of NetworkId and EID are different from the definition in phosphor-dbus-interfaces

### ISSUE THREAD

**Issue by RickyWu-wiwynn** [CodeConstruct/mctp#12]
The type of `NetworkId` and `EID` under MCTP Endpoint interface defined in phosphor-dbus-interfaces are `size`.

```
properties:
    - name: NetworkId
      type: size
      ...

    - name: EID
      type: size
      ...
```

But mctpd set the type of `NetworkId` to `i` and `EID` to `y` in `bus_endpoint_get_prop`
```
static int bus_endpoint_get_prop(sd_bus *bus,
		const char *path, const char *interface, const char *property,
		sd_bus_message *reply, void *userdata, sd_bus_error *berr)
{
	peer *peer = userdata;
	int rc;

	if (strcmp(property, "NetworkId") == 0) {
		rc = sd_bus_message_append(reply, "i", peer->net);
	} else if (strcmp(property, "EID") == 0) {
		rc = sd_bus_message_append(reply, "y", peer->eid);
        }
...
```

We have discussed this issue at [discord](https://discord.com/channels/775381525260664832/778790638563885086/1148572216875810836) that would causes issue if we use `std::get<size_t>` to get the value of the properties, and we thought that it would be better to change the type of `NetworkId` and `EID` in mctpd.

Would like to know your comments.
Thank you.

**Comment by jk-ozlabs** [comment]
Thanks for the report!

Yes, this sounds reasonable to use `y` for EID and `u` for Network. We'll look at a change for this, just need to manage backwards compatibility.

**Comment by RickyWu-wiwynn** [comment]
Thanks for your reply.
I think the type of EID should also be `u` to match the type of `size`.

**Comment by jk-ozlabs** [comment]
> I think the type of EID should also be `u` to match the type of `size`.

That's not the case on all platforms though. Why does it need to be a `size_t` ?

**Comment by RickyWu-wiwynn** [comment]
I saw [pldm](https://github.com/openbmc/pldm) use different type to get the value of `EID`.
1. mctp_eid (uint8_t): https://github.com/openbmc/pldm/blob/master/requester/mctp_endpoint_discovery.cpp#L53
2. size_t: https://github.com/openbmc/pldm/blob/master/requester/mctp_endpoint_discovery.cpp#L89

I'm testing the PLDM sensor monitor commits on gerrit and found that they changed to use size_t to get the value of `EID`.
https://gerrit.openbmc.org/c/openbmc/pldm/+/51184/46/requester/mctp_endpoint_discovery.cpp#103

I think this might need to be synchronized.

**Comment by jk-ozlabs** [comment]
Yep, agreed! We'll get some changes sorted for this, and synchronise with the OpenBMC clients there.

**Comment by khangng-ampere** [comment]
> Thanks for the report!
> 
> Yes, this sounds reasonable to use `y` for EID and `u` for Network. We'll look at a change for this, just need to manage backwards compatibility.

I can see the change from the OpenBMC side at https://github.com/openbmc/phosphor-dbus-interfaces/commit/5e7bca41c4460abb6f513ae8e0a67c551d6192a5. Can we change `mctpd` to use `u` for `NetworkId` now, or are there any backwards compatibility issue?

**Comment by RickyWu-wiwynn** [comment]
We provided PR#18 to modify the type of `NetworkId` to `u`.

**Comment by jk-ozlabs** [comment]
Fixed in https://github.com/CodeConstruct/mctp/commit/8c905939ac1663e5b6ed9388560115cdd90dcc30
