### ISSUE TITLE
MCTP over PCIe VDM

### ISSUE THREAD

**Issue by Kendidi** [CodeConstruct/mctp#21]
Hi,

I wonder will there be driver support available for sending MCTP over PCIe VDM messages to device through BMC?

Many thanks!
Ken

**Comment by jk-ozlabs** [comment]
This repo doesn't contain any transport drivers; that's all handled by the Linux kernel:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/net/mctp

\- where the current drivers are for i2c, i3c and serial.

I don't have any plans for a PCIe VDM driver currently.

**Comment by Kendidi** [comment]
I see. Can you please point me to the right direction for what will need for sending MCTP over PCIe VDM messages to device?

**Comment by jk-ozlabs** [comment]
You'll need to write a driver along the same pattern as one of those above, but interacting with the AST2600's MCTP PCIe hardware block - see section 30 of the AST2600 datasheet.

**Comment by Kendidi** [comment]
Thank you very much for your direction!  Where can I find the AST2600 datasheet?
I tried "www.aspeedtech.com" but it required login.

**Comment by Kendidi** [comment]
By the way, will AST2500 work?  Or only AST2600 will?  Thanks!

**Comment by jk-ozlabs** [comment]
You will need to create an account with aspeed for that, yes, and possibly sign an agreement for access. Not sure about 2500; I'm not sure about the status of the MCTP/PCIe hardware there.

**Comment by Kendidi** [comment]
I see.  Thank you!
Beside that, do I need the ASpeed kernel driver, ast.ko?

**Comment by jk-ozlabs** [comment]
There is no single kernel driver for the aspeed hardware; there are all sorts of individual device drivers applicable to the platform. Some of those are common, some are ast-specific.

Which ones you need will depend on what your intended device usage is.

**Comment by jk-ozlabs** [comment]
Closing as not related to these mctp userspace tools, but feel free to get in touch if you need to discuss further.

**Comment by Kendidi** [comment]
Thank you Jeremy!!

**Comment by Kendidi** [comment]
The chip maker is reluctant to provide the datasheet.  I'm not sure how to proceed now.

**Comment by Kendidi** [comment]
Hi Jeremy,

I wonder can host submit **MCTP PCIe VDM** to **AST2600**'s **MCTP Controller** registers through BAR X directly?  Or does host need to go through **PCIe Host to BMC Controller** or its **Mailbox**?  Please advise.

**Comment by jk-ozlabs** [comment]
Sorry, I have no idea how you would generate VDM messages on your host; I assume this is a matter of writing to the host's PCIe RC MMIO space to generate the appropriate VDM cycles (which sounds like the latter option there).

**Comment by Kendidi** [comment]
The VMD message bytes can be generated manually or by sw.  The problem is how to send the message out to the PCIe device though AST2600, etc.
