### ISSUE TITLE
Size of pointer taken for length check rather than sizeof structure.

### ISSUE THREAD

**Issue by jic23** [CodeConstruct/mctp#3]
https://github.com/CodeConstruct/mctp/blob/e2fe78cddf5c65a37e70b19cf8e0ee27b3b2f7df/src/mctpd.c#L1545

Breaks getting message types supported.
(otherwise touch wood this code works great - thanks!)

**Comment by mkj** [comment]
Thanks @jic23
Missed this in testing since the sizes happened to match on 32 bit platforms.
