### ISSUE TITLE
How to assign remote EID in case of I2C Mux topology?

### ISSUE THREAD

**Issue by Aritra-BITS** [CodeConstruct/mctp#35]
Firstly, I am very new to this.
My question is how to assign remote EID in case of Mux Topology.
My use case involves this particular I2C switch:

https://www.nxp.com/products/interfaces/ic-spi-i3c-interface-devices/ic-multiplexers-switches/four-channel-ic-bus-switch-with-reset:PCA9546A

Lets say i know the address of this switch from the DTS in say 0x70

I want to do something similar to 

`mctp route add 9 via mctpi2c5`

but through the said switch, because my MCTP compatible device is connected to one of these switches.

These are the output of certain commands that might help

```
$ mctp link show
dev mctpi2c5 index 4 address 0x10 net 1 mtu 254 up

```

8 is the local EID which i assigned using

```
mctp addr add 8 dev mctpi2c5
mctp link set mctpi2c5 up
```

```
$ busctl tree xyz.openbmc_project.MCTP
`-/xyz
  `-/xyz/openbmc_project
    `-/xyz/openbmc_project/mctp
      `-/xyz/openbmc_project/mctp/1
        `-/xyz/openbmc_project/mctp/1/8
```

the mctp compatible device is at 0x32

```
$ i2cdetect -y 5
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: UU -- -- -- -- -- -- -- -- -- -- -- -- -- -- UU
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- 32 -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- 61 -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: UU -- -- -- -- -- -- --
```

None of the following works as the output of busctl tree is same (for obvious reasons)

```
mctp neigh add 9 dev mctpi2c5 lladdr 0x32
mctp route add 9 via mctpi2c5
```

Edit:

Output of
`busctl introspect xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp/1/8`

is as

```
NAME                                TYPE      SIGNATURE RESULT/VALUE                           FLAGS
au.com.CodeConstruct.MCTP.Endpoint  interface -         -                                      -
.Remove                             method    -         -                                      -
.SetMTU                             method    u         -                                      -
org.freedesktop.DBus.Introspectable interface -         -                                      -
.Introspect                         method    -         s                                      -
org.freedesktop.DBus.Peer           interface -         -                                      -
.GetMachineId                       method    -         s                                      -
.Ping                               method    -         -                                      -
org.freedesktop.DBus.Properties     interface -         -                                      -
.Get                                method    ss        v                                      -
.GetAll                             method    s         a{sv}                                  -
.Set                                method    ssv       -                                      -
.PropertiesChanged                  signal    sa{sv}as  -                                      -
xyz.openbmc_project.Common.UUID     interface -         -                                      -
.UUID                               property  s         "27fcd8d6-0f22-487f-bdb7-34077be33b13" const
xyz.openbmc_project.MCTP.Endpoint   interface -         -                                      -
.EID                                property  y         8                                      const
.NetworkId                          property  i         1                                      const
.SupportedMessageTypes              property  ay        1 0                                    const
```

**Comment by Aritra-BITS** [comment]
Thank you. 

Can you explain why after running this command

`busctl call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp au.com.CodeConstruct.MCTP SetupEndpoint say mctpi2c5 1 0x32`

it got the value 9?

**Comment by Aritra-BITS** [comment]
Also is there any documentation of the said methods, I don't seem to find it anywhere?
Further, if we have to use `mctpd` to assign endpoints to remote devices, then what is this command is for?

`mctp route add 9 via mctpi2c1 `

**Comment by amboar** [comment]
> Thank you.
> 
> Can you explain why after running this command
> 
> `busctl call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp au.com.CodeConstruct.MCTP SetupEndpoint say mctpi2c5 1 0x32`
> 
> it got the value 9?

Sure! By DSP0236 v1.3.1 8.2 "Special endpoint IDs", 0x00, 0x01-0x07, and 0xff have protocol-defined meanings or are reserved. That leaves 0x08-0xfe for allocation to endpoints. If `mctpd` is running as the top-most bus owner we tend to configure the system its running on with EID 0x08. Further, `mctpd` by default assumes that all unallocated addresses participate in its dynamic EID pool. Its current allocation strategy is to allocate the first free EID in the dynamic pool to the device in question. As 0x08 is already allocated, your device got 0x09.

**Comment by jk-ozlabs** [comment]
>  Given you know the EID of the device and its location in the system relative to the buses you're using for MCTP, you can just tell the kernel where to forward packets destined for the device

.. or if your endpoint already has a statis EID configured by default, the `LearnEndpoint` call will query the device for its EID, and add the dbus objects, route and neighbour entry for you.

**Comment by Aritra-BITS** [comment]
Thanks, Everything worked fine so far. So i was messing around with other Dbus Methods, like .Remove. 
Now `busctl call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp au.com.CodeConstruct.MCTP SetupEndpoint say mctpi2c5 1 0x32` outputs false even though an EID is assigned. Maybe I need clear/flush old used EID or something equivalent?

Here are series of command that will help to assess the issue.

```
$ mctp addr add 8 dev mctpi2c5

$ busctl call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp au.com.CodeConstruct.MCTP SetupEndpoint say mctpi2c5 1 0x32
yisb 14 1 "/xyz/openbmc_project/mctp/1/14" false

$ busctl tree xyz.openbmc_project.MCTP
`-/xyz
  `-/xyz/openbmc_project
    `-/xyz/openbmc_project/mctp
      `-/xyz/openbmc_project/mctp/1
        |-/xyz/openbmc_project/mctp/1/14
        `-/xyz/openbmc_project/mctp/1/8

$ busctl introspect xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp/1/14
NAME                                TYPE      SIGNATURE RESULT/VALUE                           FLAGS
au.com.CodeConstruct.MCTP.Endpoint  interface -         -                                      -
.Remove                             method    -         -                                      -
.SetMTU                             method    u         -                                      -
org.freedesktop.DBus.Introspectable interface -         -                                      -
.Introspect                         method    -         s                                      -
org.freedesktop.DBus.Peer           interface -         -                                      -
.GetMachineId                       method    -         s                                      -
.Ping                               method    -         -                                      -
org.freedesktop.DBus.Properties     interface -         -                                      -
.Get                                method    ss        v                                      -
.GetAll                             method    s         a{sv}                                  -
.Set                                method    ssv       -                                      -
.PropertiesChanged                  signal    sa{sv}as  -                                      -
xyz.openbmc_project.Common.UUID     interface -         -                                      -
.UUID                               property  s         "740d00fc-4dae-ed11-8000-946dae570afa" const
xyz.openbmc_project.MCTP.Endpoint   interface -         -                                      -
.EID                                property  y         14                                     const
.NetworkId                          property  i         1                                      const
.SupportedMessageTypes              property  ay        4 1 2 3 5                              const



```

**Comment by amboar** [comment]
> So i was messing around with other Dbus Methods, like .Remove.
Now busctl call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp au.com.CodeConstruct.MCTP SetupEndpoint say mctpi2c5 1 0x32 outputs false even though an EID is assigned. Maybe I need clear/flush old used EID or something equivalent?

Calling `Remove` won't change the state of the remote device, rather it [removes the kernel routing and neighbour information along with the D-Bus object hosted by mctpd](https://github.com/CodeConstruct/mctp/blob/main/docs/mctpd.md#remove) ([here's the implementation](https://github.com/CodeConstruct/mctp/blob/main/src/mctpd.c#L2308) if you wish to follow along). 

The implementation of `SetupEndpoint` [tests if the device already has an EID assigned](https://github.com/CodeConstruct/mctp/blob/main/src/mctpd.c#L1786-L1796) and if so, uses that instead. In this case it will return `false` for the `assigned` value in the D-Bus response. This sounds like the code-path you're hitting.

If you want to force the remote device to take a new EID you can [use `AssignEndpoint` instead](https://github.com/CodeConstruct/mctp/blob/main/docs/mctpd.md#assignendpoint), or reset the remote device such that it forgets its previously-assigned EID.

**Comment by Aritra-BITS** [comment]
Thank you, that clarifies everything. I was able to enumerate all the remote mctp devices on the muxed i2c channel using mctpd dbus methods. This is my final dts:

#include <dt-bindings/i2c/i2c.h>


```
&i2c5 {
    status = "okay";
    bus-frequency = <400000>;
    multi-master;
    mctp-controller;
    mctp@10 {
        compatible = "mctp-i2c-controller";
        reg = <(0x10 | I2C_OWN_SLAVE_ADDRESS)>;
    };

    i2c-switch@74 {
        compatible = "nxp,pca9546";
        reg = <0x74>;
        #address-cells = <1>;
        #size-cells = <0>;
        i2c-parent = <&i2c5>;

        i2c6: i2c@0 {
            #address-cells = <1>;
            #size-cells = <0>;
            reg = <0>;
            mctp-controller;
        };

        i2c7: i2c@1 {
            #address-cells = <1>;
            #size-cells = <0>;
            reg = <1>;
            mctp-controller;
        };

        i2c8: i2c@2 {
            #address-cells = <1>;
            #size-cells = <0>;
            reg = <2>;
            mctp-controller;
        };

        i2c9: i2c@3 {
            #address-cells = <1>;
            #size-cells = <0>;
            reg = <3>;
            mctp-controller;
        };
    };
};

```

**Comment by jk-ozlabs** [comment]
Looks good!

Note that you may not need the `mctp-controller` flag on the `i2c5` node. This is only required if you have MCTP endpoints at the top-level of the bus (ie, directly connected to the i2c controller, and not behind the mux).

**Comment by Aritra-BITS** [comment]
Understood. Thanks. You may mark this as solved.
