### ISSUE TITLE
Will using the same EID for all local interfaces create any issues?

### ISSUE THREAD

**Issue by Aritra-BITS** [CodeConstruct/mctp#38]
This is not an issue, this is a question.

I am very new to openbmc and mctp.
I have an I2C bus which is further MUXed into 4 channels. There is one mctp compatible devices on each of those channels at 0x32.
This the dts entry and i2cdetect output which clarifies the same

``` 
&i2c1 {
    status = "okay";
    bus-frequency = <400000>;
    multi-master;

    mctp@10 {
        compatible = "mctp-i2c-controller";
        reg = <(0x50 | I2C_OWN_SLAVE_ADDRESS)>;
    };

    i2c-switch@70 {
        compatible = "nxp,pca9546";
        reg = <0x70>;
        #address-cells = <1>;
        #size-cells = <0>;
        i2c-parent = <&i2c1>;

        i2c2: i2c@0 {
            #address-cells = <1>;
            #size-cells = <0>;
            reg = <0>;
            mctp-controller;
        };

        i2c3: i2c@1 {
            #address-cells = <1>;
            #size-cells = <0>;
            reg = <1>;
            mctp-controller;
        };

        i2c4: i2c@2 {
            #address-cells = <1>;
            #size-cells = <0>;
            reg = <2>;
            mctp-controller;
        };

        i2c5: i2c@3 {
            #address-cells = <1>;
            #size-cells = <0>;
            reg = <3>;
            mctp-controller;
        };
    };
}; 
```

i2cdetect for i2c bus 2 (its same for bus 3,4 and 5)

```
~# i2cdetect -y 2
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: UU -- -- 13 -- -- -- -- -- -- -- -- -- -- -- UU
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- 32 -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: 50 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- 61 -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: UU -- -- -- -- -- -- --
```

Now in order to setup a local interface at bus2, I do the following (the remote device has an EID of 101):

```
~# mctp address add 8 dev mctpi2c2
~# mctp link set mctpi2c2 up
~# mctp neigh add 101 dev mctpi2c2 lladdr 0x32
```

I create a dbus object of the same
```
~# busctl call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp au.com.CodeConstruct.MCTP LearnEndpoint say mctpi2c2 1 0x32
yisb 101 1 "/xyz/openbmc_project/mctp/1/101" true
```

Now my question is. Can i use the same EID (here 8) for all the local interfaces of the buses? When I tried to run `mctp address add 8 dev mctpi2c2`. It executed without any issue. And i was able to create dbus object like above as well, no issues at all. Now lets say we move a little forward trying various things for instance PLDM commands. Will this create any issues? Simply, is this a good practice?

**Comment by jk-ozlabs** [comment]
> Can i use the same EID (here 8) for all the local interfaces of the buses?

Yep! That's somewhat an expected use-case.

You can assign different addresses, but if a single address makes more sense for your network layout, then that's fine too.

**Comment by Aritra-BITS** [comment]
Thank you for the clarification.
