### ISSUE TITLE
Has header "linux/mctp.h" No

### ISSUE THREAD

**Issue by AfteratiadLily** [CodeConstruct/mctp#4]
Hi  I'm totally beginner and have a question.When complie this code, it seems  couldn't find "mctp.h".but this file does exist. 
![Screenshot from 2022-07-19 16-31-49](https://user-images.githubusercontent.com/92743357/179879820-e5f5f6cc-47b5-48b0-97d0-2a30cba936a9.png)
I try redownload and complie again same report.  It's normal and it will influence the function?
Thank you

**Comment by mkj** [comment]
That message is normal - the `mctp.h` Linux kernel header was only added recently so hasn't made its way to libc headers on some systems. If it is missing mctp will use its own internal header file instead.

**Comment by jk-ozlabs** [comment]
Sounds like this is addressed, so closing. @AfteratiadLily , feel free to re-open if you need.
