### ISSUE TITLE
Dangling instruction in endpoint recovery lifecycle documentation 

### ISSUE THREAD

**Issue by mdmillerii** [CodeConstruct/mctp#47]
I was browsing this repository and found the documentation for tracking endpoint lifecycle has a dangling step instructioning to `Issue` but then has no further text on what to issue or how to issue.

https://github.com/CodeConstruct/mctp/blob/f9a5618e16377ba107ec09d7673c6af2694ba8af/docs/endpoint-recovery.md?plain=1#L372

This appears to be in the initial commit of this file and not an edit removing content.

**Comment by mdmillerii** [comment]
I'm just browsing and not trying to consume the documentation to implement code at this time.

**Comment by jk-ozlabs** [comment]
Milton! Nice to see you here. Thanks for the report.

@amboar, was there something intended to go here? or should this step be removed?

**Comment by amboar** [comment]
I'll send a PR to remove the dangling step.
