### ISSUE TITLE
Which Linux kernel version does this MCTP code depend on？

### ISSUE THREAD

**Issue by lbbxsxlz** [CodeConstruct/mctp#5]
When I try to build this project, I find some undeclared  macros. So I want to know this code depended on which Linux kernel version.
Thanks!

**Comment by jk-ozlabs** [comment]
You'll probably need 5.16 or later for running `mctp` or `mctpd`. For compiling, it's more the headers that we rely on, but we *should* be OK without those, as there is a set of compatibility macros in `mctp.h`

Can you paste the errors you're seeing?

**Comment by lbbxsxlz** [comment]
> You'll probably need 5.16 or later for running `mctp` or `mctpd`. For compiling, it's more the headers that we rely on, but we _should_ be OK without those, as there is a set of compatibility macros in `mctp.h`
> 
> Can you paste the errors you're seeing?

"
ninja: Entering directory `obj'
[1/3] Compiling C object mctp.p/src_mctp-netlink.c.o
FAILED: mctp.p/src_mctp-netlink.c.o
ccache cc -Imctp.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -g -Wno-unused-parameter -MD -MQ mctp.p/src_mctp-netlink.c.o -MF mctp.p/src_mctp-netlink.c.o.d -o mctp.p/src_mctp-netlink.c.o -c ../src/mctp-netlink.c
../src/mctp-netlink.c: In function ‘open_nl_socket’:
../src/mctp-netlink.c:80:35: error: ‘NETLINK_GET_STRICT_CHK’ undeclared (first use in this function); did you mean ‘NETLINK_GENERIC’?
  rc = setsockopt(sd, SOL_NETLINK, NETLINK_GET_STRICT_CHK,
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   NETLINK_GENERIC
../src/mctp-netlink.c:80:35: note: each undeclared identifier is reported only once for each function it appears in
[2/3] Compiling C object mctp.p/src_mctp.c.o
FAILED: mctp.p/src_mctp.c.o
ccache cc -Imctp.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -g -Wno-unused-parameter -MD -MQ mctp.p/src_mctp.c.o -MF mctp.p/src_mctp.c.o.d -o mctp.p/src_mctp.c.o -c ../src/mctp.c
../src/mctp.c:107:3: error: ‘IFLA_MIN_MTU’ undeclared here (not in a function); did you mean ‘IFLA_MTU’?
  [IFLA_MIN_MTU] = "IFLA_MIN_MTU",
   ^~~~~~~~~~~~
   IFLA_MTU
../src/mctp.c:107:3: error: array index in initializer not of integer type
../src/mctp.c:107:3: note: (near initialization for ‘ifla_attrnames’)
../src/mctp.c:108:3: error: ‘IFLA_MAX_MTU’ undeclared here (not in a function); did you mean ‘IFLA_MIN_MTU’?
  [IFLA_MAX_MTU] = "IFLA_MAX_MTU",
   ^~~~~~~~~~~~
   IFLA_MIN_MTU
../src/mctp.c:108:3: error: array index in initializer not of integer type
../src/mctp.c:108:3: note: (near initialization for ‘ifla_attrnames’)
../src/mctp.c:109:3: error: ‘IFLA_PROP_LIST’ undeclared here (not in a function); did you mean ‘IFLA_BROADCAST’?
  [IFLA_PROP_LIST] = "IFLA_PROP_LIST",
   ^~~~~~~~~~~~~~
   IFLA_BROADCAST
../src/mctp.c:109:3: error: array index in initializer not of integer type
../src/mctp.c:109:3: note: (near initialization for ‘ifla_attrnames’)
../src/mctp.c:110:3: error: ‘IFLA_ALT_IFNAME’ undeclared here (not in a function); did you mean ‘IFLA_IFNAME’?
  [IFLA_ALT_IFNAME] = "IFLA_ALT_IFNAME",
   ^~~~~~~~~~~~~~~
   IFLA_IFNAME
../src/mctp.c:110:3: error: array index in initializer not of integer type
../src/mctp.c:110:3: note: (near initialization for ‘ifla_attrnames’)
../src/mctp.c:111:3: error: ‘IFLA_PERM_ADDRESS’ undeclared here (not in a function); did you mean ‘IFLA_ADDRESS’?
  [IFLA_PERM_ADDRESS] = "IFLA_PERM_ADDRESS",
   ^~~~~~~~~~~~~~~~~
   IFLA_ADDRESS
../src/mctp.c:111:3: error: array index in initializer not of integer type
../src/mctp.c:111:3: note: (near initialization for ‘ifla_attrnames’)
../src/mctp.c:112:3: error: ‘IFLA_PROTO_DOWN_REASON’ undeclared here (not in a function); did you mean ‘IFLA_PROTO_DOWN’?
  [IFLA_PROTO_DOWN_REASON] = "IFLA_PROTO_DOWN_REASON",
   ^~~~~~~~~~~~~~~~~~~~~~
   IFLA_PROTO_DOWN
../src/mctp.c:112:3: error: array index in initializer not of integer type
../src/mctp.c:112:3: note: (near initialization for ‘ifla_attrnames’)
../src/mctp.c:125:3: error: ‘IFA_RT_PRIORITY’ undeclared here (not in a function); did you mean ‘IFLA_BR_PRIORITY’?
  [IFA_RT_PRIORITY] = "IFA_RT_PRIORITY",
   ^~~~~~~~~~~~~~~
   IFLA_BR_PRIORITY
../src/mctp.c:125:3: error: array index in initializer not of integer type
../src/mctp.c:125:3: note: (near initialization for ‘ifa_attrnames’)
../src/mctp.c:126:3: error: ‘IFA_TARGET_NETNSID’ undeclared here (not in a function); did you mean ‘IFLA_NEW_NETNSID’?
  [IFA_TARGET_NETNSID] = "IFA_TARGET_NETNSID",
   ^~~~~~~~~~~~~~~~~~
   IFLA_NEW_NETNSID
../src/mctp.c:126:3: error: array index in initializer not of integer type
../src/mctp.c:126:3: note: (near initialization for ‘ifa_attrnames’)
../src/mctp.c:142:3: error: ‘NDA_PROTOCOL’ undeclared here (not in a function); did you mean ‘SO_PROTOCOL’?
  [NDA_PROTOCOL] = "NDA_PROTOCOL",
   ^~~~~~~~~~~~
   SO_PROTOCOL
../src/mctp.c:142:3: error: array index in initializer not of integer type
../src/mctp.c:142:3: note: (near initialization for ‘nda_attrnames’)
../src/mctp.c:143:3: error: ‘NDA_NH_ID’ undeclared here (not in a function); did you mean ‘NDA_VNI’?
  [NDA_NH_ID] = "NDA_NH_ID",
   ^~~~~~~~~
   NDA_VNI
../src/mctp.c:143:3: error: array index in initializer not of integer type
../src/mctp.c:143:3: note: (near initialization for ‘nda_attrnames’)
../src/mctp.c:144:3: error: ‘NDA_FDB_EXT_ATTRS’ undeclared here (not in a function)
  [NDA_FDB_EXT_ATTRS] = "NDA_FDB_EXT_ATTRS",
   ^~~~~~~~~~~~~~~~~
../src/mctp.c:144:3: error: array index in initializer not of integer type
../src/mctp.c:144:3: note: (near initialization for ‘nda_attrnames’)
ninja: build stopped: subcommand failed.
"

I think these errors may be related to the kernel version of the host.
My current kernel version of host is 4.15.

**Comment by jk-ozlabs** [comment]
Oh wow, yeah, that's quite old now; it's not just the MCTP headers that are missing, there are also generic netlink defines missing too.

Can you build on a more recent kernel? Keep in mind that you'll need to be running this on 5.16+ in order to use any MCTP communication too...

**Comment by lbbxsxlz** [comment]
> Oh wow, yeah, that's quite old now; it's not just the MCTP headers that are missing, there are also generic netlink defines missing too.
> 
> Can you build on a more recent kernel? Keep in mind that you'll need to be running this on 5.16+ in order to use any MCTP communication too...

Thanks, I will retry on 5.16+.
