### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by santoshpuranik** [CodeConstruct/mctp#56]
I am opening this issue to discuss possible mechanisms for mctpd to report errors encountered during any of the standard MCTP control flows. Some examples where it is desirable to have error handling:

* Failures/timeouts in any of the standard MCTP control messages such as `SetEndpointID`, `GetEndpointID`, `AllocateEndpointIDs` etc..
* Failures in determining the endpoint properties such as message types and UUID.

Currently, the mctpd code uses warnx() to output errors to stdout. However, platforms utilizing an OpenBMC stack would find the need to create more structured error log events for one or more of the above scenarios.

How do you think mctpd should report errors? Does something like emitting a D-Bus signal that can be handled by an orchestrator application like mctp reactor sound like a good approach?

**Comment by jk-ozlabs** [comment]
The interactions you have listed will be a part of a dbus call from some other application, in which case the error would be reported as a call failure there.

Keep in mind that mctpd will not be a part of general interactions with a device once is it initialised; its main role is in the enumeration and setup of endpoints. Other services which actually interact with those endpoints would typically be better placed to monitor for errors. This has driven the error recovery implementation that @amboar has worked on (see https://github.com/CodeConstruct/mctp/blob/main/docs/endpoint-recovery.md)

Do you have any specific scenarios you can share, to help with a suitable design?

**Comment by santoshpuranik** [comment]
Thanks for the response, Jeremy. I agree that for an interaction that involves an external application like the mctp reactor triggering a D-Bus call, error scenarios will be seen as failures on the D-Bus API. There seem to be specific scenarios such as errors from `query_peer_properties` seem to be ignored.

Is that on purpose? That we publish an endpoint object with no fully populated messagetypes/uuid and that can be taken to mean an error?

If yes, then I think the rest seem to be covered already.

I agree that the recovery implementation can handle scenarios where an endpoint stops responding after the discovery is already completed.

**Comment by jk-ozlabs** [comment]
Hi Santosh,

> There seem to be specific scenarios such as errors from query_peer_properties seem to be ignored.
>
> Is that on purpose? That we publish an endpoint object with no fully populated messagetypes/uuid and that can be taken to mean an error?

That is somewhat intentional, for a couple of reasons:

 * the Get Endpoint UUID command is not mandatory to implement in all cases (ref Table 12 of DSP0236)
 * the Get Message Type Support command is mandatory, but we have seen endpoint devices that do not support it. In this case, we can still list the endpoint on dbus, but (of course) it will not report support for any message types.

Either way, failures from either are fairly straightforward to detect on the consumer side.

**Comment by santoshpuranik** [comment]
> Either way, failures from either are fairly straightforward to detect on the consumer side.

Ack. I think I can close this issue now. The general direction is any error conditions need to be propagated to consumers via either explicit errors from the D-Bus methods OR indirectly communicated via missing/incomplete D-Bus endpoint objects. That seems reasonable. Thanks, Jeremy.
