### ISSUE TITLE
end point enabling steps/documentation ?

### ISSUE THREAD

**Issue by caripepo** [CodeConstruct/mctp#9]
I'm unable to find a clear example of how to add end points and better yet how to find the correct physical address of a pci device to manage my end points. What I'm trying to achieve is to associate an nvme storage device and see how is the interaction with the nvme-cli tool using a mctp address instead of using the "/dev/nvmeXnY" space. I do notice that under "/sys/block/nvme0n1/device/device/uevent" there are values making refence to the PCI address, I will assume that in the example below my device address is "0000:e6:00.0" but even so what are the correct steps to use the "mctp" to registered (mctp link OR mctp address ??) and then to be able to use it along with the nvme-cli tool.

ex, /sys/block/nvme0n1/device/device/uevent
---
DRIVER=nvme
PCI_CLASS=14800
PCI_ID=6087:0B60
PCI_SUBSYS_ID=6087:7D08
PCI_SLOT_NAME=0000:a9:00.0
MODALIAS=pci:v00006087d00000B60sv00006086sd00008ED08be01sc18o02
---

as of nvme-cli 2.2.1 I see the refence done to being able to see a drive using the mctp protocol. 
---
nvme-2.2.1
usage: nvme $command $device $args

The '<device>' may be either an NVMe character device (ex: /dev/nvme0), an
nvme block device (ex: /dev/nvme0n1), or a mctp address in the form
mctp:<net>,<eid>[:ctrl-id]
---

Any other documentation will be gladly appreciated.

**Comment by jk-ozlabs** [comment]
I'm not 100% clear on what you're trying to do here: if you have a PCIe connection to the nvme device, you don't really need the MCTP channel for management. In a typical setup, there is no PCIe connection to the NVMe-MI device at all, only  NVMe-MI over MCTP over SMBus.

If you definitely do want to use NVMe-MI over MCTP, keep in mind it is completely separate from the PCIe channel: none of the PCIe bus addressing will tell you how the SMBus addressing works. You'll need to separately initialise the MCTP network.

I have some documentation for doing this setup (for firmware updates, but would work for any NVMe-MI commands), up at:

  https://codeconstruct.com.au/docs/nvme-mi-firmware-update/

As an example, this is a little script that I use to manually set up endpoint communication with a NVMe-MI device with SMBus address `0x1d`, connected to MCTP interface `mctpi2c0`:

```sh
mctp addr add 8 dev mctpi2c0
mctp link set mctpi2c0 up
mctp link set mctpi2c0 mtu 254
systemctl restart mctpd
busctl --no-pager call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp au.com.CodeConstruct.MCTP SetupEndpoint say mctpi2c0 1 0x1d
```

That `SetupEndpoint` call will assign an MCTP EID to the device and return the new EID (probably 9, the first available EID by default), after which you should be able to manage the device using something like:

```
nvme id-ctrl mctp:1,9
```

**Comment by caripepo** [comment]
Hey thanks for your response. Just to add more context to what I am trying to achieve here. I would like to get debug data specifically smart-logs but while the nvme drive is using the spdk driver not nvme. When drive is using the spdk driver the nvme drive gets relinquish from the user space and nvme-cli is not able to see it. Now fast forward, I want to be able to interact with the drive using your steps to see if possible.

**Comment by jk-ozlabs** [comment]
OK, cool, thanks for the detail.

So: do you have a SMBus connection to the drive? Do you know if it supports MCTP over SMBus?

**Comment by caripepo** [comment]
I was under the impression I answer your question sorry for the long delay. Not sure how to configure smbus, but looking at the output given to me using nvme-cli tool it return that is supported. To be able to communicte to the drive and allow this support would I require extra hardware like a i2c/spi host adapte or something that would allow me to connect it through smbus??. On the other hand I was able to achieve what I was looking for. Using the xnvme tool it has default spdk support out of box and I am able to talk to my nvme drive as I would expect as if I were using the nvme-cli tool.
xnvme looks for devices not only "/dev" space but using pci adresses in the form of bus function id. xnvme calleds them uri addresses. With that said when using the spdk driver on my nvme drive I am able to get smart-logs or other features similar to nvme-cli.

**Comment by jk-ozlabs** [comment]
Yes, if you're looking to use the currently-supported MCTP-over-SMBus interface, you would definitely need a SMBus connection to the device.

Good that you have got it working over PCIe though, closing here.
